export const matchupsConstants = {
  INDEX_REQUEST: 'MATCHUPS_INDEX_REQUEST',
  INDEX_SUCCESS: 'MATCHUPS_INDEX_SUCCESS',
  INDEX_FAILURE: 'MATCHUPS_INDEX_FAILURE',

  CREATE_REQUEST: 'CREATE_MATCHUP_REQUEST',
  CREATE_SUCCESS: 'CREATE_MATCHUP_SUCCESS',
  CREATE_FAILURE: 'CREATE_MATCHUP_FAILURE',

  UPDATE_REQUEST: 'UPDATE_MATCHUP_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_MATCHUP_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_MATCHUP_FAILURE',

  DESTROY_REQUEST: 'DESTROY_MATCHUP_REQUEST',
  DESTROY_SUCCESS: 'DESTROY_MATCHUP_SUCCESS',
  DESTROY_FAILURE: 'DESTROY_MATCHUP_FAILURE'
}