export const matchupConstants = {
  SHOW_REQUEST: 'MATCHUP_SHOW_REQUEST',
  SHOW_SUCCESS: 'MATCHUP_SHOW_SUCCESS',
  SHOW_FAILURE: 'MATCHUP_SHOW_FAILURE',

  CREATE_INVITATION_REQUEST: 'MATCHUP_CREATE_INVITATION_REQUEST',
  CREATE_INVITATION_SUCCESS: 'MATCHUP_CREATE_INVITATION_SUCCESS',
  CREATE_INVITATION_FAILURE: 'MATCHUP_CREATE_INVITATION_FAILURE',

  UPDATE_INVITATION_REQUEST: 'MATCHUP_UPDATE_INVITATION_REQUEST',
  UPDATE_INVITATION_SUCCESS: 'MATCHUP_UPDATE_INVITATION_SUCCESS',
  UPDATE_INVITATION_FAILURE: 'MATCHUP_UPDATE_INVITATION_FAILURE',

  DESTROY_INVITATION_REQUEST: 'MATCHUP_DESTROY_INVITATION_REQUEST',
  DESTROY_INVITATION_SUCCESS: 'MATCHUP_DESTROY_INVITATION_SUCCESS',
  DESTROY_INVITATION_FAILURE: 'MATCHUP_DESTROY_INVITATION_FAILURE'
}